### ISSUE TITLE
MemCache implementation

### ISSUE THREAD

**Issue by canmogol** [canmogol/FatJar#3]
https://github.com/canmogol/FatJar/blob/master/src/main/java/fatjar/implementations/cache/MemCache.java

**Comment by Onurus** [comment]
MemCache Java Client Interface implemented (by @ayhanugurlu )
You can configure server(s) in memcache.properties file with comma(,)
Engineering tests applied but could not write unit test because of difficulties comes from memcache service install and startup issues.
