### ISSUE TITLE
RedisCache implementation

### ISSUE THREAD

**Issue by canmogol** [canmogol/FatJar#4]
https://github.com/canmogol/FatJar/blob/master/src/main/java/fatjar/implementations/cache/RedisCache.java

**Comment by ayhanugurlu** [comment]
RedisCache was implemented.

**Comment by canmogol** [comment]
"FatJar/src/main/java/fatjar/implementations/cache/RedisCache.java" contains dummy implementation

**Comment by ayhanugurlu** [comment]
RedisCache was implemented.
